os:
  - linux
  - osx
  
sudo: false

language: perl

# normally cpanm is called for perl, but we do not need it so skip the installation of dependencies
install:
  - git clone https://github.com/riywo/anyenv ~/.anyenv
  - export PATH="$HOME/.anyenv/bin:$PATH"
  - echo 'eval "$(anyenv init -)"' >~/.bashrc
  - source ~/.bashrc
  - anyenv install plenv
  - source ~/.bashrc

script:
  - perl -v
  - prove ./test.sh
